name: Public pull request checks 📥

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - release*

permissions:
  contents: read

jobs:
  quality_checks:
    name: Public quality checks 👌🧪
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/__quality_checks.yml
    permissions:
      contents: read
    with:
      commit: ${{ github.event.pull_request.head.sha }}

  product_identity:
    name: Product identity 🪪
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/__product_identity.yml
    permissions:
      contents: read
    with:
      commit: ${{ github.event.pull_request.head.sha }}
